export interface AuthResponse {
  ok: boolean;
  id?: string;
  name?: string;
  email?: string;
  token?: string;
  msg?: string;

}
export interface AccountType {
  accountTypeID?: string;
  type?: string;

}
/*
export interface User {
  UserID?: number;
  FirstName: string;
  MiddleName?: string;
  LastName: string;
  EmailAddress: string;
  MobilePhone: string;
  Last4DigitsSSN: string;
  TermsandConditions: boolean;
  MaxLoginAttempt?: number;
  LastLogin?: Date;
  Status: string;
  EnrolledDate: Date;
  Password?: string;
}
*/
// Generated by https://quicktype.io

export interface Employee {
  user:   User;
  role:   string;
  salary: number;
}

export interface User {
  userID:             number;
  firstName:          string;
  middleName:         string;
  lastName:           string;
  emailAddress:       string;
  mobilePhone:        string;
  last4DigitsSSN:     number;
  termsandConditions: boolean;
  maxLoginAttempt:    number;
  lastLogin:          null;
  status:             string;
  enrolledDate:       string;
  password:           string;
  employee:           null;
}

/*
export interface User {
  UserID?: number;
  FirstName: string;
  MiddleName?: string;
  LastName: string;
  EmailAddress: string;
  MobilePhone: string;
  Last4DigitsSSN: string;
  TermsandConditions: boolean;
  MaxLoginAttempt?: number;
  LastLogin?: Date;
  Status: string;
  EnrolledDate: Date;
}
*/















